apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: readthedocs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: readthedocs
        tier: backend
    spec:
      containers:
      - name: readthedocs
        image: suanmeiguo/readthedocs:latest
        resources:
          requests:
            cpu: 0.5
            memory: 2024Mi
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        ports:
        # Jetty server
        - containerPort: 8000
        # internal grpc server
      imagePullSecrets:
        - name: appstore-backend-secret

---

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: readthedocs
  labels:
    app: readthedocs
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: readthedocs
    tier: backend
