kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: readthedocs-dev-pvc
  namespace: dev
  annotations:
    volume.beta.kubernetes.io/storage-class: manual
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi