apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev
  name: readthedocs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: readthedocs
        tier: backend
    spec:
      containers:
      - name: readthedocs
        image: registry-corp.hypereal.com/public/readthedocs:v3
        resources:
          requests:
            cpu: 0.5
            memory: 2024Mi
        env:
        - name: PRODUCTION_DOMAIN
          value: docs-dev.hypereal.com
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /data
          name: readthedocs-dev-volume
      imagePullSecrets:
        - name: appstore-backend-secret
      volumes:
      - name: readthedocs-dev-volume
        persistentVolumeClaim:
          claimName: readthedocs-dev-pvc

---

apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: readthedocs
  labels:
    app: readthedocs
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30525
  selector:
    app: readthedocs
    tier: backend
