kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-readthedocs-volume1
  namespace: dev
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-071e0b9b4503f2cd7
    fsType: ext4